services:
  discord-bot:
    container_name: 'jambot-main'
    hostname: 'discord-bot'
    image: 'python:3.12'
    volumes:
      - './:/app'
    working_dir: /app
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - SPOTIFY_CID=${SPOTIFY_CID}
      - SPOTIFY_SECRET=${SPOTIFY_SECRET}
      - LYRICS_GENIUS_TOKEN=${LYRICS_GENIUS_TOKEN}
    env_file:
      - path: .env
        required: false
    restart: no
    deploy:
      resources:
        limits:
          memory: 2G
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        apt-get -y update
        apt-get -y upgrade
        apt-get install -y --no-install-recommends ffmpeg
        pip install --root-user-action ignore -r requirements.txt
        python -u musicBot.py